TEST - loop emulator test, disable appcenter test

diff --git a/tools/ci_build/github/azure-pipelines/templates/android-java-api-aar-test.yml b/tools/ci_build/github/azure-pipelines/templates/android-java-api-aar-test.yml
--- a/tools/ci_build/github/azure-pipelines/templates/android-java-api-aar-test.yml
+++ b/tools/ci_build/github/azure-pipelines/templates/android-java-api-aar-test.yml
@@ -62,23 +62,39 @@ jobs:
       cd ./android
       mkdir -p app/libs
       cp $(Build.BinariesDirectory)/final-android-aar/${{parameters.packageName}}-$(OnnxRuntimeVersion).aar app/libs/onnxruntime-mobile.aar
-      $(Build.SourcesDirectory)/java/gradlew --no-daemon clean connectedDebugAndroidTest --info --stacktrace
+
+      NUM_ITERATIONS=10
+      NUM_FAILURES=0
+      for (( i = 0 ; i < $NUM_ITERATIONS ; i++ ))
+      do
+        echo "*** test iteration $i"
+
+        $(Build.SourcesDirectory)/java/gradlew --no-daemon clean connectedDebugAndroidTest --info --stacktrace
+
+        TEST_RESULT=$?
+        if [[ "$TEST_RESULT" -ne 0 ]]; then
+          echo "*** failure at test iteration $i"
+          ((NUM_FAILURES++))
+        fi
+      done
+      echo "*** failed iterations: ${NUM_FAILURES} / ${NUM_ITERATIONS}"
+      exit $NUM_FAILURES
     displayName: Run E2E test using Emulator
     workingDirectory: $(Build.BinariesDirectory)
 
-  - script: |
-      set -e -x
-      cd android_test/android
-      appcenter test run espresso \
-        --app "AI-Frameworks/ORT-Mobile-Android" \
-        --devices $(app_center_android_test_devices) \
-        --app-path ./app/build/outputs/apk/debug/app-debug.apk \
-        --test-series "master" \
-        --locale "en_US" \
-        --build-dir ./app/build/outputs/apk/androidTest/debug \
-        --token $(app_center_api_token)
-    displayName: Run E2E tests using App Center
-    workingDirectory: $(Build.BinariesDirectory)
+  # - script: |
+  #     set -e -x
+  #     cd android_test/android
+  #     appcenter test run espresso \
+  #       --app "AI-Frameworks/ORT-Mobile-Android" \
+  #       --devices $(app_center_android_test_devices) \
+  #       --app-path ./app/build/outputs/apk/debug/app-debug.apk \
+  #       --test-series "master" \
+  #       --locale "en_US" \
+  #       --build-dir ./app/build/outputs/apk/androidTest/debug \
+  #       --token $(app_center_api_token)
+  #   displayName: Run E2E tests using App Center
+  #   workingDirectory: $(Build.BinariesDirectory)
 
   - script: |
       python3 $(Build.SourcesDirectory)/tools/python/run_android_emulator.py \
