[WebGPU plugin EP] Add Win ARM64 Python package (#28526)
<!-- Describe your changes. -->

- Add WebGPU plugin EP Windows ARM64 Python package build and test
- Disable unit test building in packaging pipeline to reduce build time

<!-- - Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here. -->

Add Windows ARM64 Python package.

diff --git a/tools/ci_build/github/azure-pipelines/plugin-webgpu-pipeline.yml b/tools/ci_build/github/azure-pipelines/plugin-webgpu-pipeline.yml
--- a/tools/ci_build/github/azure-pipelines/plugin-webgpu-pipeline.yml
+++ b/tools/ci_build/github/azure-pipelines/plugin-webgpu-pipeline.yml
@@ -63,9 +63,6 @@ variables:
   # Path (relative to the repository root) of the VERSION_NUMBER file used for plugin package versioning.
   - name: epVersionFile
     value: plugin-ep-webgpu/VERSION_NUMBER
-  # Windows ARM64 build requires Windows x64 build to be enabled (ARM64 cross-compilation depends on x64 build artifacts)
-  - name: invalidARM64Config
-    value: ${{ and(eq(parameters.build_windows_arm64, true), eq(parameters.build_windows_x64, false)) }}
   # Non-dev package versions (release, RC) must use Release build type
   - name: invalidBuildTypeConfig
     value: ${{ and(ne(parameters.package_version, 'dev'), ne(parameters.cmake_build_type, 'Release')) }}
@@ -100,7 +97,7 @@ extends:
 
     stages:
       # Validate parameter combinations
-      - ${{ if or(eq(variables['invalidARM64Config'], 'True'), eq(variables['invalidBuildTypeConfig'], 'True')) }}:
+      - ${{ if eq(variables['invalidBuildTypeConfig'], 'True') }}:
         - stage: Validate_Parameters
           displayName: 'Validate Parameters'
           dependsOn: []
@@ -112,16 +109,10 @@ extends:
               os: windows
             steps:
             - checkout: none
-            - ${{ if eq(variables['invalidARM64Config'], 'True') }}:
-              - script: |
-                  echo "##vso[task.logissue type=error]Windows ARM64 build requires Windows x64 build to be enabled."
-                  exit 1
-                displayName: 'ERROR: Windows ARM64 requires Windows x64'
-            - ${{ if eq(variables['invalidBuildTypeConfig'], 'True') }}:
-              - script: |
-                  echo "##vso[task.logissue type=error]Non-dev package version requires Release build type."
-                  exit 1
-                displayName: 'ERROR: Non-dev package version requires Release build type'
+            - script: |
+                echo "##vso[task.logissue type=error]Non-dev package version requires Release build type."
+                exit 1
+              displayName: 'ERROR: Non-dev package version requires Release build type'
       - ${{ else }}:
         - template: stages/plugin-webgpu-packaging-stage.yml
           parameters:
