Move set common variable to stage

diff --git a/tools/ci_build/github/azure-pipelines/templates/stages/mac-ios-packaging-build-stage.yml b/tools/ci_build/github/azure-pipelines/templates/stages/mac-ios-packaging-build-stage.yml
--- a/tools/ci_build/github/azure-pipelines/templates/stages/mac-ios-packaging-build-stage.yml
+++ b/tools/ci_build/github/azure-pipelines/templates/stages/mac-ios-packaging-build-stage.yml
@@ -7,8 +7,6 @@ parameters:
 
 stages:
 - stage: IosPackaging_Build_${{ parameters.packageVariant }}
-  dependsOn:
-  - IosPackaging_SetCommonVariables
   jobs:
   - job:
     displayName: "Build iOS package for variant: ${{ parameters.packageVariant}}"
@@ -42,6 +40,37 @@ stages:
         targetPath: $(Build.ArtifactStagingDirectory)
         artifactName: browserstack_test_artifacts_${{ lower(parameters.packageVariant) }}
     steps:
+    - bash: |
+        set -e
+
+        BUILD_TYPE="${{ parameters.buildType }}"
+        BASE_VERSION="$(cat ./VERSION_NUMBER)"
+        SHORT_COMMIT_HASH="$(git rev-parse --short HEAD)"
+        DEV_VERSION="${BASE_VERSION}-dev+$(Build.BuildNumber).${SHORT_COMMIT_HASH}"
+
+        case "${BUILD_TYPE}" in
+          ("release")
+            VERSION="${BASE_VERSION}" ;;
+          ("normal")
+            VERSION="${DEV_VERSION}" ;;
+          (*)
+            echo "Invalid build type: ${BUILD_TYPE}"; exit 1 ;;
+        esac
+
+        # Do not output ##vso[] commands with `set -x` or they may be parsed again and include a trailing quote.
+        set +x
+
+        set_var() {
+          local VAR_NAME=${1:?}
+          local VAR_VALUE=${2:?}
+          echo "##vso[task.setvariable variable=${VAR_NAME};isoutput=true;isreadonly=true]${VAR_VALUE}"
+          echo "${VAR_NAME}: ${VAR_VALUE}"
+        }
+
+        set_var "ORT_POD_VERSION" "${VERSION}"
+      displayName: "Set common variables"
+      name: SetCommonVariables
+
     - script: |
         if [[ -z "$(ortPodVersion)" ]]; then
           echo "ORT pod version is unspecified. Make sure that the IosPackaging_SetCommonVariables stage has run."
