update

diff --git a/tools/ci_build/github/linux/docker/manylinux.patch b/tools/ci_build/github/linux/docker/manylinux.patch
--- a/tools/ci_build/github/linux/docker/manylinux.patch
+++ b/tools/ci_build/github/linux/docker/manylinux.patch
@@ -50,6 +50,17 @@ index 961e34d..55ae11b 100755
      make install > /dev/null
  }
  
+diff --git a/finalize.sh b/finalize.sh
+index 621eab9..4cbcf90 100755
+--- a/finalize.sh
++++ b/finalize.sh
+@@ -86,6 +86,3 @@ clean_pyc /opt/_internal
+ rm -rf /root/.cache
+ 
+ hardlink -cv /opt/_internal
+-
+-# update system packages
+-LC_ALL=C ${MY_DIR}/update-system-packages.sh
 diff --git a/install-build-packages.sh b/install-build-packages.sh
 index 408bc33..b45ceba 100755
 --- a/install-build-packages.sh
@@ -83,7 +94,7 @@ index 9ef1e99..ec52833 100755
 +fi
 \ No newline at end of file
 diff --git a/install-runtime-packages.sh b/install-runtime-packages.sh
-index 137d2e2..4be0e79 100755
+index 137d2e2..4269afb 100755
 --- a/install-runtime-packages.sh
 +++ b/install-runtime-packages.sh
 @@ -33,7 +33,7 @@ source $MY_DIR/build_utils.sh
@@ -119,7 +130,7 @@ index 137d2e2..4be0e79 100755
  	elif [ "${AUDITWHEEL_ARCH}" == "aarch64" ] || [ "${AUDITWHEEL_ARCH}" == "ppc64le" ] || [ "${AUDITWHEEL_ARCH}" == "s390x" ]; then
  		# Software collection (for devtoolset-10)
  		yum -y install centos-release-scl-rh
-@@ -86,7 +88,7 @@ if [ "${AUDITWHEEL_POLICY}" == "manylinux2014" ]; then
+@@ -86,19 +88,18 @@ if [ "${AUDITWHEEL_POLICY}" == "manylinux2014" ]; then
  	fi
  elif [ "${AUDITWHEEL_POLICY}" == "manylinux_2_28" ]; then
  	PACKAGE_MANAGER=dnf
@@ -128,9 +139,10 @@ index 137d2e2..4be0e79 100755
  	# See https://unix.stackexchange.com/questions/41784/can-yum-express-a-preference-for-x86-64-over-i386-packages
  	echo "multilib_policy=best" >> /etc/yum.conf
  	# Error out if requested packages do not exist
-@@ -95,10 +97,10 @@ elif [ "${AUDITWHEEL_POLICY}" == "manylinux_2_28" ]; then
+ 	echo "skip_missing_names_on_install=False" >> /etc/yum.conf
+ 	# Make sure that locale will not be removed
  	sed -i '/^override_install_langs=/d' /etc/yum.conf
- 	dnf -y upgrade
+-	dnf -y upgrade
  	dnf -y install dnf-plugins-core
 -	dnf config-manager --set-enabled powertools # for yasm
 -	TOOLCHAIN_DEPS="gcc-toolset-12-binutils gcc-toolset-12-gcc gcc-toolset-12-gcc-c++ gcc-toolset-12-gcc-gfortran"
@@ -143,3 +155,16 @@ index 137d2e2..4be0e79 100755
  	fi
  elif [ "${AUDITWHEEL_POLICY}" == "musllinux_1_1" ]; then
  	TOOLCHAIN_DEPS="binutils gcc g++ gfortran"
+@@ -121,12 +122,6 @@ else
+ 	exit 1
+ fi
+ 
+-# update system packages, we already updated them but
+-# the following script takes care of cleaning-up some things
+-# and since it's also needed in the finalize step, everything's
+-# centralized in this script to avoid code duplication
+-LC_ALL=C ${MY_DIR}/update-system-packages.sh
+-
+ if [ "${BASE_POLICY}" == "manylinux" ]; then
+ 	# we'll be removing libcrypt.so.1 later on
+ 	# this is needed to ensure the new one will be found
