Reenable nuget test

diff --git a/tools/ci_build/github/azure-pipelines/nuget/templates/test_macos.yml b/tools/ci_build/github/azure-pipelines/nuget/templates/test_macos.yml
--- a/tools/ci_build/github/azure-pipelines/nuget/templates/test_macos.yml
+++ b/tools/ci_build/github/azure-pipelines/nuget/templates/test_macos.yml
@@ -34,16 +34,15 @@ stages:
         packageFolder: '$(Build.BinariesDirectory)/nuget-artifact'
 
     - script: |
-        echo "TODO: Enable this test once fix this nuget test issue"
-  #     $(Build.SourcesDirectory)/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests/runtest.sh \
-  #               $(Build.BinariesDirectory)/nuget-artifact \
-  #               $(NuGetPackageVersionNumber) \
-  #               ${{ parameters.IsMacOS }}
-  #
-  #     if [ $? -ne 0 ]; then
-  #         echo "Failed to run test"
-  #         exit 1
-  #     fi
+       $(Build.SourcesDirectory)/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests/runtest.sh \
+                 $(Build.BinariesDirectory)/nuget-artifact \
+                 $(NuGetPackageVersionNumber) \
+                 ${{ parameters.IsMacOS }}
+
+       if [ $? -ne 0 ]; then
+           echo "Failed to run test"
+           exit 1
+       fi
       displayName: 'Run Test'
       env:
           OnnxRuntimeBuildDirectory: $(Build.BinariesDirectory)
