update

diff --git a/tools/ci_build/github/azure-pipelines/nuget/templates/test_macos.yml b/tools/ci_build/github/azure-pipelines/nuget/templates/test_macos.yml
--- a/tools/ci_build/github/azure-pipelines/nuget/templates/test_macos.yml
+++ b/tools/ci_build/github/azure-pipelines/nuget/templates/test_macos.yml
@@ -11,19 +11,20 @@ stages:
     workspace:
       clean: all
     pool:
-      name: 'Azure Pipelines'
-      image: 'macOS-14'
-      os: 'macOS'
+      vmImage: 'macOS-15'
 
     variables:
     - name: OnnxRuntimeBuildDirectory
       value: '$(Build.BinariesDirectory)'
     steps:
-    - task: DownloadPipelineArtifact@0
-      displayName: 'Download Pipeline Artifact - Signed NuGet'
-      inputs:
-        artifactName: drop-signed-nuget-${{ parameters.ArtifactSuffix }}
-        targetPath: '$(Build.BinariesDirectory)/nuget-artifact'
+    - download: build
+      displayName: 'Download Nuget'
+      artifact: 'drop-signed-nuget-${{ parameters.ArtifactSuffix }}'
+
+
+    - script: |
+        mv $(Pipeline.Workspace)/build/drop-signed-nuget-${{ parameters.ArtifactSuffix }} $(Build.BinariesDirectory)/nuget-artifact
+  
 
     - task: DownloadPipelineArtifact@0
       displayName: 'Download OsX CustomOp test data'
@@ -36,16 +37,16 @@ stages:
         packageFolder: '$(Build.BinariesDirectory)/nuget-artifact'
 
     - script: |
-        echo "TODO: Enable this test once fix this nuget test issue"
-  #     $(Build.SourcesDirectory)/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests/runtest.sh \
-  #               $(Build.BinariesDirectory)/nuget-artifact \
-  #               $(NuGetPackageVersionNumber) \
-  #               ${{ parameters.IsMacOS }}
-  #
-  #     if [ $? -ne 0 ]; then
-  #         echo "Failed to run test"
-  #         exit 1
-  #     fi
+       echo "TODO: Enable this test once fix this nuget test issue"
+       $(Build.SourcesDirectory)/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests/runtest.sh \
+                 $(Build.BinariesDirectory)/nuget-artifact \
+                 $(NuGetPackageVersionNumber) \
+                 true
+  
+       if [ $? -ne 0 ]; then
+           echo "Failed to run test"
+           exit 1
+       fi
       displayName: 'Run Test'
       env:
           OnnxRuntimeBuildDirectory: $(Build.BinariesDirectory)
