qnn test conditional android test build

diff --git a/tools/ci_build/github/azure-pipelines/templates/jobs/download_linux_qnn_sdk.yml b/tools/ci_build/github/azure-pipelines/templates/jobs/download_linux_qnn_sdk.yml
--- a/tools/ci_build/github/azure-pipelines/templates/jobs/download_linux_qnn_sdk.yml
+++ b/tools/ci_build/github/azure-pipelines/templates/jobs/download_linux_qnn_sdk.yml
@@ -17,6 +17,21 @@ steps:
     displayName: 'Print QnnSDKRootDir after downloading QNN SDK'
 
   - script: |
+      sdk_file="$(QnnSDKRootDir)/sdk.yaml"
+      qnn_sdk_version=$(grep '^version:' "$sdk_file" | head -n 1 | cut -d':' -f2 | xargs | cut -d'.' -f1-3)
+      if [[ -n "$qnn_sdk_version" ]]; then
+        echo "##vso[task.setvariable variable=QnnSDKVersionYaml]$qnn_sdk_version"
+      else
+        echo "Version not found in sdk.yaml."
+        exit 1
+      fi
+    displayName: Set QnnSDKVersionYaml based on sdk.yaml
+
+  - bash: |
+      echo "QnnSDKVersionYaml=$(QnnSDKVersionYaml)"
+    displayName: 'Print QnnSDKVersionYaml after extracting from sdk.yaml'
+
+  - script: |
       azcopy cp --recursive 'https://lotusscus.blob.core.windows.net/models/qnnsdk/Qualcomm AI Hub Proprietary License.pdf' $(QnnSDKRootDir)
     displayName: 'Download Qualcomm AI Hub license'
 
